In [1]:
import pandas as pd

df = pd.read_csv("C:\Yazılım\Pandas\players_22.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (25,108) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
#İlk 5 Oyuncunun Bilgileri

result = df.head(5)

result

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [3]:
#Listede Kaç Tane Oyuncu Var

result = len(df.index)
result

19239

In [4]:
#Oyuncuların Yaş Ortalaması

result = df["age"].mean()
result

25.210821768283175

In [5]:
#En Yaşlı Oyuncu

result = df["age"].max()

In [6]:
#En Yaşlı Oyuncunun İsmi

result = df[df["age"]==df["age"].max()]["short_name"].iloc[0]
result

'K. Miura'

In [7]:
#Yaşı 15-20 Aralığında Olan Oyuncuların Adı ve Takım Listesi

result = df[(df["age"] >= 15) & (df["age"] <= 20)][["age","short_name","league_name","club_name","overall","potential"]].head(10)
result

,age,short_name,league_name,club_name,overall,potential
29,20,E. Haaland,German 1. Bundesliga,Borussia Dortmund,88,93
274,20,A. Davies,German 1. Bundesliga,FC Bayern München,82,89
387,18,Pedri,Spain Primera Division,FC Barcelona,81,91
499,20,Vinícius Jr.,Spain Primera Division,Real Madrid CF,80,90
508,19,B. Saka,English Premier League,Arsenal,80,88
656,20,Rodrygo,Spain Primera Division,Real Madrid CF,79,88
661,18,J. Bellingham,German 1. Bundesliga,Borussia Dortmund,79,89
854,19,R. Gravenberch,Holland Eredivisie,Ajax,78,90
855,19,M. Greenwood,English Premier League,Manchester United,78,89
859,18,E. Camavinga,Spain Primera Division,Real Madrid CF,78,89

In [8]:
#Galatasaray takımındaki ilk 10 oyuncu

result = df[df["club_name"] == "Galatasaray SK"][["short_name","overall"]].head(10)
result

          short_name  overall
403       F. Muslera       80
1069          Marcão       77
1175  P. van Aanholt       76
1475        R. Babel       75
1521     S. Feghouli       75
1894    C. Luyindama       75
2176       M. Diagne       74
2419      M. Mohamed       74
2686       D. Yedlin       73
2800    T. Antalyalı       73

In [9]:
#Premier Ligdeki En İyi 20 Oyuncu

result = df[df["league_name"] == "English Premier League"][["short_name","age","overall","potential"]].head(20)
result

             short_name  age  overall  potential
2     Cristiano Ronaldo   36       91         91
4          K. De Bruyne   30       91         91
9               H. Kane   27       90         90
10             N. Kanté   30       90         90
13               H. Son   28       89         89
15          V. van Dijk   29       89         89
16              S. Mané   29       89         89
17             M. Salah   29       89         89
18              Ederson   27       89         91
20              Alisson   28       89         90
25            R. Lukaku   28       88         88
27          R. Sterling   26       88         89
28      Bruno Fernandes   26       88         89
31            H. Lloris   34       87         87
37             P. Pogba   28       87         87
42         A. Robertson   27       87         88
44  T. Alexander-Arnold   22       87         92
45            J. Sancho   21       87         91
46           Rúben Dias   24       87         91
51               Thiago   30       86         86